name: 'Netlify CLI'
description: 'Run commands with Netlify CLI'
inputs:
  command:
    description: 'Netlify CLI command'
    required: true
runs:
  using: 'docker'
  image: docker://ghcr.io/valueourminds/netlify-cli-action/netlify-cli:latest
  args:
    - '${{ inputs.command }}'
